# Generated by Django 3.2.7 on 2021-09-08 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contentInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corporate_logo', models.ImageField(blank=True, default=False, max_length=255, null=True, upload_to='home_page', verbose_name='Şirket logosu')),
            ],
            options={
                'verbose_name': 'Anasayfa Bilgileri',
                'verbose_name_plural': 'Anasayfa Bilgileri',
            },
        ),
    ]
