# Generated by Django 3.2.7 on 2021-09-08 10:35

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentinput',
            name='about_descriptions',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Hakkımızda Açıklama'),
        ),
        migrations.AddField(
            model_name='contentinput',
            name='about_image',
            field=models.ImageField(blank=True, default=False, max_length=255, null=True, upload_to='home_page', verbose_name='Hakkımızda Resim'),
        ),
        migrations.AddField(
            model_name='contentinput',
            name='branch_adress',
            field=models.TextField(blank=True, null=True, verbose_name='Şube Ofis Adresi'),
        ),
        migrations.AddField(
            model_name='contentinput',
            name='branch_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Şube Ofis Email'),
        ),
        migrations.AddField(
            model_name='contentinput',
            name='branch_local_link',
            field=models.TextField(blank=True, null=True, verbose_name='Şube Ofis Konum Linki'),
        ),
        migrations.AddField(
            model_name='contentinput',
            name='branch_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Şube Ofis Telefon'),
        ),
        migrations.AddField(
            model_name='contentinput',
            name='central_address',
            field=models.TextField(blank=True, null=True, verbose_name='Merkez Ofis Adres'),
        ),
        migrations.AddField(
            model_name='contentinput',
            name='central_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Merekez Ofis Email'),
        ),
        migrations.AddField(
            model_name='contentinput',
            name='central_local_link',
            field=models.TextField(blank=True, null=True, verbose_name='Merkez Ofis Konum Linki'),
        ),
        migrations.AddField(
            model_name='contentinput',
            name='central_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Merekez Ofis Telefon'),
        ),
        migrations.AddField(
            model_name='contentinput',
            name='corporate_descriptions',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Kurumsal Üst Ana Açıklama'),
        ),
        migrations.AddField(
            model_name='contentinput',
            name='corporate_home_image',
            field=models.ImageField(blank=True, default=False, max_length=255, null=True, upload_to='home_page', verbose_name='Anasayfa Kurumsal Resim'),
        ),
        migrations.AddField(
            model_name='contentinput',
            name='corporate_image',
            field=models.ImageField(blank=True, default=False, max_length=255, null=True, upload_to='home_page', verbose_name='Kurumsal Çözümler'),
        ),
        migrations.AddField(
            model_name='contentinput',
            name='corporate_solve',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Kurumsal Çözümler'),
        ),
        migrations.AddField(
            model_name='contentinput',
            name='eudaimonia',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Eudaimonia Health & Fitness'),
        ),
        migrations.AddField(
            model_name='contentinput',
            name='eudaimonia_image',
            field=models.ImageField(blank=True, default=False, max_length=255, null=True, upload_to='home_page', verbose_name='Eudaimonia Health & Fitness'),
        ),
        migrations.AddField(
            model_name='contentinput',
            name='fitness',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Fitness Monitor'),
        ),
        migrations.AddField(
            model_name='contentinput',
            name='fitness_image',
            field=models.ImageField(blank=True, default=False, max_length=255, null=True, upload_to='home_page', verbose_name='Fitness Monitor'),
        ),
        migrations.AddField(
            model_name='contentinput',
            name='fitskill',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='FitSkill Sağlık & Yetenek Karnesi'),
        ),
        migrations.AddField(
            model_name='contentinput',
            name='fitskill_image',
            field=models.ImageField(blank=True, default=False, max_length=255, null=True, upload_to='home_page', verbose_name='FitSkill Sağlık & Yetenek Karnesi'),
        ),
        migrations.AddField(
            model_name='contentinput',
            name='founder',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Kurucu Açıklama'),
        ),
        migrations.AddField(
            model_name='contentinput',
            name='founder_image',
            field=models.ImageField(blank=True, default=False, max_length=255, null=True, upload_to='home_page', verbose_name='Kurucu Fotoğrafı'),
        ),
        migrations.AddField(
            model_name='contentinput',
            name='founder_name_surname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kurucu Adı ve Soyadı'),
        ),
        migrations.AddField(
            model_name='contentinput',
            name='learnbetter',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='LearnBetter E-Öğrenme'),
        ),
        migrations.AddField(
            model_name='contentinput',
            name='learnbetter_image',
            field=models.ImageField(blank=True, default=False, max_length=255, null=True, upload_to='home_page', verbose_name='LearnBetter E-Öğrenme'),
        ),
        migrations.AddField(
            model_name='contentinput',
            name='philosophy',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Felsefe Açıklama'),
        ),
        migrations.AddField(
            model_name='contentinput',
            name='philosophy_image',
            field=models.ImageField(blank=True, default=False, max_length=255, null=True, upload_to='home_page', verbose_name='Felsefe Resim'),
        ),
        migrations.AddField(
            model_name='contentinput',
            name='software_descriptions',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Yazılımlarımız Üst Ana açıklama'),
        ),
        migrations.AddField(
            model_name='contentinput',
            name='title_slider_descriptions',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Slider Resim Alt Başlık'),
        ),
    ]
