# Generated by Django 3.2.7 on 2021-09-08 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20210908_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Slider Resim Ana Başlıkları')),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to='home_page', verbose_name='Slider Resimleri')),
                ('home', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.contentinput', verbose_name='Slider Resimleri')),
            ],
            options={
                'verbose_name': 'Slider Resim Ekle',
                'verbose_name_plural': 'Slider Resim Ekle',
            },
        ),
    ]
