# Generated by Django 3.2.7 on 2021-09-08 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_imagepost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentinput',
            name='about_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='home_page', verbose_name='Hakkımızda Resim'),
        ),
        migrations.AlterField(
            model_name='contentinput',
            name='corporate_home_image',
            field=models.ImageField(max_length=255, null=True, upload_to='home_page', verbose_name='Anasayfa Kurumsal Resim'),
        ),
        migrations.AlterField(
            model_name='contentinput',
            name='corporate_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='home_page', verbose_name='Kurumsal Çözümler'),
        ),
        migrations.AlterField(
            model_name='contentinput',
            name='corporate_logo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='home_page', verbose_name='Şirket logosu'),
        ),
        migrations.AlterField(
            model_name='contentinput',
            name='eudaimonia_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='home_page', verbose_name='Eudaimonia Health & Fitness'),
        ),
        migrations.AlterField(
            model_name='contentinput',
            name='fitness_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='home_page', verbose_name='Fitness Monitor'),
        ),
        migrations.AlterField(
            model_name='contentinput',
            name='fitskill_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='home_page', verbose_name='FitSkill Sağlık & Yetenek Karnesi'),
        ),
        migrations.AlterField(
            model_name='contentinput',
            name='founder_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='home_page', verbose_name='Kurucu Fotoğrafı'),
        ),
        migrations.AlterField(
            model_name='contentinput',
            name='learnbetter_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='home_page', verbose_name='LearnBetter E-Öğrenme'),
        ),
        migrations.AlterField(
            model_name='contentinput',
            name='philosophy_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='home_page', verbose_name='Felsefe Resim'),
        ),
    ]
