# Generated by Django 3.2.7 on 2021-09-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20210908_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentinput',
            name='corporate_home_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='home_page', verbose_name='Anasayfa Kurumsal Resim'),
        ),
    ]
