# Generated by Django 3.2.7 on 2021-09-09 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_contentinput_corporate_home_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentinput',
            name='eudaimonia_link',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Eudaimonia Link Alanı'),
        ),
        migrations.AddField(
            model_name='contentinput',
            name='eudaimonia_link_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Eudaimonia link adı'),
        ),
        migrations.AddField(
            model_name='contentinput',
            name='fitness_link',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Fitness Link Alanı'),
        ),
        migrations.AddField(
            model_name='contentinput',
            name='fitness_link_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Fitness link adı'),
        ),
        migrations.AddField(
            model_name='contentinput',
            name='fitskill_link',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='FitSkill Link Alanı'),
        ),
        migrations.AddField(
            model_name='contentinput',
            name='fitskill_link_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='FitSkill link adı'),
        ),
        migrations.AddField(
            model_name='contentinput',
            name='learnbetter_link',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='LearnBetter Link Alanı'),
        ),
        migrations.AddField(
            model_name='contentinput',
            name='learnbetter_link_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Learnbetter link adı'),
        ),
    ]
