# Generated by Django 3.2.7 on 2021-09-09 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_auto_20210909_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentinput',
            name='founder_link',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Kurucu web link alanı'),
        ),
    ]
