# Generated by Django 3.2.7 on 2021-09-09 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_contentinput_founder_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentinput',
            name='founder_link_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Kurucu Websiitesi link adı'),
        ),
        migrations.AlterField(
            model_name='contentinput',
            name='founder_link',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Kurucu Websitesi link alanı'),
        ),
    ]
