# Generated by Django 3.2.7 on 2021-09-09 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_auto_20210909_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepost',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='home_page', verbose_name='Slider Resimleri'),
        ),
    ]
