# Generated by Django 3.2.7 on 2021-09-09 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_alter_imagepost_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepost',
            name='image',
            field=models.ImageField(max_length=255, null=True, upload_to='home_page', verbose_name='Slider Resimleri'),
        ),
    ]
