# Generated by Django 3.2.7 on 2021-09-30 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_alter_imagepost_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentinput',
            name='corporate_home_image',
        ),
        migrations.RemoveField(
            model_name='contentinput',
            name='title_slider_descriptions',
        ),
    ]
