# Generated by Django 3.2.7 on 2021-09-30 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_auto_20210930_0956'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(blank=True, max_length=250, null=True, verbose_name='Ana Başlık Açıklama')),
                ('name_surname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ad ve Soyad')),
                ('job', models.CharField(blank=True, max_length=100, null=True, verbose_name='Uğraş Alanı')),
                ('personal_descriptions', models.CharField(blank=True, max_length=150, null=True, verbose_name='Kişi hakkında kısa açıklama')),
                ('instagram', models.CharField(blank=True, max_length=100, null=True, verbose_name='Instagram Link')),
                ('twitter', models.CharField(blank=True, max_length=100, null=True, verbose_name='Twitter Link')),
                ('facebook', models.CharField(blank=True, max_length=100, null=True, verbose_name='Facebook Link')),
                ('mail', models.CharField(blank=True, max_length=100, null=True, verbose_name='Mail Address')),
                ('image', models.ImageField(max_length=255, null=True, upload_to='home_page/upload_image', verbose_name='Slider Resimleri')),
            ],
            options={
                'verbose_name': 'Ekip Adaylarını Ekle',
                'verbose_name_plural': 'Ekip Adaylarını Ekle',
            },
        ),
        migrations.RemoveField(
            model_name='imagepost',
            name='title',
        ),
        migrations.AddField(
            model_name='imagepost',
            name='main_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Slider Ana Başlık'),
        ),
        migrations.AddField(
            model_name='imagepost',
            name='sub_title',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='Slider Alt Başlık'),
        ),
    ]
