# Generated by Django 3.2.7 on 2021-09-30 08:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_auto_20210930_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(blank=True, max_length=250, null=True, verbose_name='Blog Haber Başlığı')),
                ('blog_descriptions', models.CharField(blank=True, max_length=250, null=True, verbose_name='Blog Haber Kısa Açıklaması')),
                ('blog_date', models.DateField(default=datetime.datetime(2021, 9, 30, 11, 26, 44, 818637))),
                ('blog_image', models.ImageField(max_length=255, null=True, upload_to='home_page/upload_image/blog_image', verbose_name='Slider Resimleri')),
            ],
            options={
                'verbose_name': 'Blog Haberleri Ekle',
            },
        ),
        migrations.RemoveField(
            model_name='contentinput',
            name='software_descriptions',
        ),
        migrations.RemoveField(
            model_name='team',
            name='main_title',
        ),
        migrations.AddField(
            model_name='contentinput',
            name='blog_main_title',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Blog Üst Ana açıklama'),
        ),
        migrations.AddField(
            model_name='contentinput',
            name='corporate_main_title',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Yazılımlarımız Ana Başlık Açıklama'),
        ),
        migrations.AddField(
            model_name='contentinput',
            name='software_main_title',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Yazılımlarımız Üst Ana açıklama'),
        ),
        migrations.AddField(
            model_name='contentinput',
            name='team_main_title',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Ekibimiz Üst Ana açıklama'),
        ),
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(max_length=255, null=True, upload_to='home_page/upload_image/team_image', verbose_name='Slider Resimleri'),
        ),
    ]
