# Generated by Django 3.2.7 on 2021-09-30 09:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_auto_20210930_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_date',
            field=models.DateField(default=datetime.datetime(2021, 9, 30, 12, 50, 35, 409615)),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_descriptions',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='Blog Haber Kısa Açıklaması'),
        ),
        migrations.AlterField(
            model_name='contentinput',
            name='blog_main_title',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='Blog Üst Ana açıklama'),
        ),
        migrations.AlterField(
            model_name='contentinput',
            name='corporate_main_title',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='Yazılımlarımız Ana Başlık Açıklama'),
        ),
        migrations.AlterField(
            model_name='contentinput',
            name='software_main_title',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='Yazılımlarımız Üst Ana açıklama'),
        ),
        migrations.AlterField(
            model_name='contentinput',
            name='team_main_title',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='Ekibimiz Üst Ana açıklama'),
        ),
        migrations.AlterField(
            model_name='imagepost',
            name='image',
            field=models.ImageField(max_length=255, null=True, upload_to='home_page/upload_image/slider_image', verbose_name='Slider Resimleri'),
        ),
        migrations.AlterField(
            model_name='team',
            name='personal_descriptions',
            field=models.TextField(blank=True, max_length=150, null=True, verbose_name='Kişi hakkında kısa açıklama'),
        ),
    ]
