# Generated by Django 3.2.7 on 2021-09-30 12:13

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_auto_20210930_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corporate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_title', models.CharField(blank=True, max_length=150, null=True, verbose_name='Ana Sayfa Başlığı')),
                ('corporate_title', models.CharField(blank=True, max_length=150, null=True, verbose_name='İçerik Başlığı')),
                ('corporate_description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Açıklama')),
                ('blog_image', models.ImageField(max_length=255, null=True, upload_to='home_page/upload_image/corporate_image', verbose_name='Kurumsal Resimler')),
            ],
            options={
                'verbose_name': 'Kurumsal Alanı Bilgileri(Kurucu,Felsefe vb ...)',
                'verbose_name_plural': 'Kurumsal Alanı Bilgileri(Kurucu,Felsefe vb ...)',
            },
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True, verbose_name='Yazılım Başlığı')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Yazılım Açıklaması')),
                ('link', models.CharField(blank=True, max_length=150, null=True, verbose_name='Yazılım web linki')),
                ('blog_image', models.ImageField(max_length=255, null=True, upload_to='home_page/upload_image/software_image', verbose_name='Kurumsal Resimler')),
            ],
            options={
                'verbose_name': 'Yazılım Alanı Bilgileri',
                'verbose_name_plural': 'Yazılım Alanı Bilgileri',
            },
        ),
        migrations.RemoveField(
            model_name='contentinput',
            name='corporate_image',
        ),
        migrations.RemoveField(
            model_name='contentinput',
            name='corporate_solve',
        ),
        migrations.RemoveField(
            model_name='contentinput',
            name='eudaimonia',
        ),
        migrations.RemoveField(
            model_name='contentinput',
            name='eudaimonia_image',
        ),
        migrations.RemoveField(
            model_name='contentinput',
            name='eudaimonia_link',
        ),
        migrations.RemoveField(
            model_name='contentinput',
            name='eudaimonia_link_name',
        ),
        migrations.RemoveField(
            model_name='contentinput',
            name='fitness',
        ),
        migrations.RemoveField(
            model_name='contentinput',
            name='fitness_image',
        ),
        migrations.RemoveField(
            model_name='contentinput',
            name='fitness_link',
        ),
        migrations.RemoveField(
            model_name='contentinput',
            name='fitness_link_name',
        ),
        migrations.RemoveField(
            model_name='contentinput',
            name='fitskill',
        ),
        migrations.RemoveField(
            model_name='contentinput',
            name='fitskill_image',
        ),
        migrations.RemoveField(
            model_name='contentinput',
            name='fitskill_link',
        ),
        migrations.RemoveField(
            model_name='contentinput',
            name='fitskill_link_name',
        ),
        migrations.RemoveField(
            model_name='contentinput',
            name='founder',
        ),
        migrations.RemoveField(
            model_name='contentinput',
            name='founder_image',
        ),
        migrations.RemoveField(
            model_name='contentinput',
            name='learnbetter',
        ),
        migrations.RemoveField(
            model_name='contentinput',
            name='learnbetter_image',
        ),
        migrations.RemoveField(
            model_name='contentinput',
            name='learnbetter_link',
        ),
        migrations.RemoveField(
            model_name='contentinput',
            name='learnbetter_link_name',
        ),
        migrations.RemoveField(
            model_name='contentinput',
            name='philosophy',
        ),
        migrations.RemoveField(
            model_name='contentinput',
            name='philosophy_image',
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_date',
            field=models.DateField(default=datetime.datetime(2021, 9, 30, 15, 13, 4, 467517)),
        ),
        migrations.AlterField(
            model_name='imagepost',
            name='image',
            field=models.ImageField(max_length=255, null=True, upload_to='home_page/upload_image/corporate_image', verbose_name='Slider Resimleri'),
        ),
    ]
