# Generated by Django 3.2.7 on 2021-10-01 07:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_auto_20210930_1513'),
    ]

    operations = [
        migrations.RenameField(
            model_name='corporate',
            old_name='blog_image',
            new_name='corporate_image',
        ),
        migrations.RemoveField(
            model_name='corporate',
            name='corporate_title',
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_date',
            field=models.DateField(default=datetime.datetime(2021, 10, 1, 10, 23, 29, 776689)),
        ),
    ]
