# Generated by Django 3.2.7 on 2021-10-01 07:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0018_auto_20211001_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentinput',
            name='facebook',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name=' Kurum Facebook Link'),
        ),
        migrations.AddField(
            model_name='contentinput',
            name='instagram',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kurum Instagram Link'),
        ),
        migrations.AddField(
            model_name='contentinput',
            name='mail',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kurum Mail Address'),
        ),
        migrations.AddField(
            model_name='contentinput',
            name='twitter',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kurum Twitter Link'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_date',
            field=models.DateField(default=datetime.datetime(2021, 10, 1, 10, 55, 53, 963410)),
        ),
    ]
