# Generated by Django 3.2.7 on 2021-10-01 08:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0020_auto_20211001_1104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='software',
            old_name='blog_image',
            new_name='software_image',
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_date',
            field=models.DateField(default=datetime.datetime(2021, 10, 1, 11, 19, 32, 457423)),
        ),
    ]
