# Generated by Django 3.2.7 on 2021-10-01 13:49

import datetime
from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0022_auto_20211001_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_date',
            field=models.DateField(default=datetime.datetime(2021, 10, 1, 16, 49, 46, 856252)),
        ),
        migrations.AlterField(
            model_name='software',
            name='software_image',
            field=stdimage.models.StdImageField(max_length=255, null=True, upload_to='home_page/upload_image/software_image', verbose_name='Kurumsal Resimler'),
        ),
    ]
