# Generated by Django 3.2.7 on 2021-10-01 15:16

import datetime
from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0024_alter_blog_blog_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_date',
            field=models.DateField(default=datetime.datetime(2021, 10, 1, 18, 16, 47, 778894)),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_image',
            field=stdimage.models.StdImageField(max_length=255, null=True, upload_to='home_page/upload_image/blog_image', verbose_name='Slider Resimleri'),
        ),
        migrations.AlterField(
            model_name='corporate',
            name='corporate_image',
            field=stdimage.models.StdImageField(max_length=255, null=True, upload_to='home_page/upload_image/corporate_image', verbose_name='Kurumsal Resimler'),
        ),
        migrations.AlterField(
            model_name='imagepost',
            name='image',
            field=stdimage.models.StdImageField(max_length=255, null=True, upload_to='home_page/upload_image/corporate_image', verbose_name='Slider Resimleri'),
        ),
        migrations.AlterField(
            model_name='team',
            name='image',
            field=stdimage.models.StdImageField(max_length=255, null=True, upload_to='home_page/upload_image/team_image', verbose_name='Slider Resimleri'),
        ),
    ]
