# Generated by Django 3.2.7 on 2021-10-01 15:20

import datetime
from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0025_auto_20211001_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_date',
            field=models.DateField(default=datetime.datetime(2021, 10, 1, 18, 20, 58, 787076)),
        ),
        migrations.AlterField(
            model_name='contentinput',
            name='about_image',
            field=stdimage.models.StdImageField(blank=True, max_length=255, null=True, upload_to='home_page', verbose_name='Hakkımızda Resim'),
        ),
    ]
