# Generated by Django 3.2.7 on 2021-10-01 15:43

import datetime
from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0028_alter_blog_blog_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_date',
            field=models.DateField(default=datetime.datetime(2021, 10, 1, 18, 43, 35, 160683)),
        ),
        migrations.AlterField(
            model_name='contentinput',
            name='about_image',
            field=stdimage.models.StdImageField(blank=True, max_length=255, null=True, upload_to='home_page/upload_images/about_images', verbose_name='Hakkımızda Resim'),
        ),
    ]
