# Generated by Django 3.2.7 on 2021-10-08 08:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0030_alter_blog_blog_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='sendMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_surname', models.CharField(blank=True, max_length=150, null=True, verbose_name='Ad Soyad')),
                ('mail', models.EmailField(blank=True, max_length=150, null=True, verbose_name='mail')),
                ('subject', models.CharField(blank=True, max_length=150, null=True, verbose_name='Konu')),
                ('message', models.TextField(blank=True, max_length=500, null=True, verbose_name='Mesaj')),
            ],
            options={
                'verbose_name': 'Kullnıcı Mesajları',
                'verbose_name_plural': 'Kullnıcı Mesajları',
            },
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_date',
            field=models.DateField(default=datetime.datetime(2021, 10, 8, 11, 29, 20, 931275)),
        ),
    ]
